### ISSUE TITLE
Thank you note

### ISSUE THREAD

**Issue by allenanie** [BurntSushi/ty#3]
Hi, this is not exactly an issue, but just want to have a place to say THANK YOU! Having to implement an interface (3 functions) in Go to sort is not fun at all, and I worry if I wrote the correct code or not all the time. This library has been a life saver! Thank you.

**Comment by BurntSushi** [comment]
I frankly wouldn't recommend using this library. It was mostly an experiment. If you use this library, then you will pay:
1. By not writing idiomatic Go.
2. By writing code that is usually an order of magnitude slower than idiomatic code.

**Comment by allenanie** [comment]
I thought Go's Reflect would be faster than Java's Reflect, but I guess that's not true. The idiomatic way to write Go sort is to "lift" a plain data structure into a type, and implement three functions. I can't say I'm not annoyed by many disposable types floating around my code and functions that only serve one purpose.

Since I'm not sorting a million records (at most 50 or 100), I think a bit of slow-down is tolerable. I'm already regretting using Go to write my web backend. I read the latest article of your blog is on Rust. How is Rust? Is there a reputable Rust-based web backend (or HTTP routing library)? At least Rust has generics.

**Comment by BurntSushi** [comment]
Please don't start a language holy war on my issue tracker. I like Go and Rust. If you want to have a conversation about Rust, then you can email me.

My recommendation stands. Use at your own peril.

**Comment by BurntSushi** [comment]
Status of web dev in Rust: http://arewewebyet.com
